/*THIS DELETES THE TABLE AND ALL DEPENDENT TABLES*/
DROP TABLE public.users CASCADE;

/*THIS DELETES THE TABLE BUT WILL NOT RUN SUCCESSFULLY IF THERE ARE ANY DEPENDENT TABLES */
DROP TABLE public.users;
